# Generated by Django 4.1.7 on 2023-02-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_description_remove_user_usertype_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuctionModel',
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
