from django.db import models
import datetime
from django.core.validators import MinValueValidator
# from django.contrib.postgres.fields import ArrayField
# from django.conf import settings
from authapp.models import User

# lets us explicitly set upload path and filename
def upload_to(instance, filename):
    return 'images/{filename}'.format(filename=filename)

# class Description(models.Model):
#     description_brand = models.CharField(max_length = 255, blank = False)
#     description_model_number = models.CharField(max_length = 255)
#     description_date_of_purchase = models.DateTimeField()
#     description_location = models.CharField(max_length = 255)
    # description_additional_accessories = ArrayField(models.CharField(max_length=255), blank=True)
    # description_additional_info = ArrayField(models.CharField(max_length=255), blank=True)



class AuctionModel(models.Model):

    # id -> autogenerated

    # blank=False, so the field is required

    name = models.CharField(max_length = 255, blank = False)
    auction_date = models.DateField(validators = [MinValueValidator(datetime.date.today)], blank = False)
    description = models.TextField()
    # description = models.OneToOneField(Description, blank = False, on_delete = PROTECT)
    # description = models.OneToOneField(Description, models.SET_NULL, blank = True, null = True ) # nullable ForeignKey -> set null when the referenced object is deleted
    base_price = models.IntegerField(blank = False)

    # tags = ArrayField(models.CharField(max_length=200), blank=True) # ArrayField only available in PostgreSQL

    description_brand = models.CharField(max_length = 255, blank = False)
    description_model_number = models.CharField(max_length = 255)
    description_date_of_purchase = models.DateTimeField()
    description_location = models.CharField(max_length = 255)

    # description_additional_accessories = ArrayField(models.CharField(max_length=255), blank=True)

    # description_additional_info = ArrayField(models.CharField(max_length=255), blank=True)
    
    owner = models.ForeignKey(
        # settings.AUTH_USER_MODEL, # check this also
        User, on_delete = models.CASCADE)
    date_published = models.DateTimeField(auto_now_add = True, editable = False) # auto_now_add -> inherit editable=False -> will not show up in the admin panel
    date_modified = models.DateTimeField(auto_now = True)

    # images - multiple later, single for now
    # image_url = models.ImageField(upload_to=upload_to, blank=True, null=True)

    def __str__(self):
        return self.name
