# Generated by Django 4.1.7 on 2023-05-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_questionmodel_bidmodel_answermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='auction_images')),
            ],
        ),
        migrations.AddField(
            model_name='auctionmodel',
            name='images',
            field=models.ManyToManyField(blank=True, to='main.image'),
        ),
    ]
